// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Delivery.Models;

namespace Delivery.Data
{
    public partial class deliveryContext : DbContext
    {
        public deliveryContext()
        {
        }

        public deliveryContext(DbContextOptions<deliveryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }

        /*protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=delivery;Integrated Security=True");
            }
        }*/

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Modern_Spanish_CI_AS");

            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.HasKey(e => e.IdCliente);

                entity.HasIndex(e => e.UserName, "IX_Cliente")
                    .IsUnique();

                entity.HasIndex(e => e.Password, "IX_Cliente_1")
                    .IsUnique();

                entity.Property(e => e.IdCliente).ValueGeneratedNever();

                entity.Property(e => e.Nit)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.RazonSocial)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.LocalidadNavigation)
                    .WithMany(p => p.Cliente)
                    .HasForeignKey(d => d.Localidad)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Cliente_Localidad");
            });

            modelBuilder.Entity<DetallePedido>(entity =>
            {
                entity.HasKey(e => e.IdDetallePedido);

                entity.Property(e => e.IdDetallePedido).ValueGeneratedNever();

                entity.Property(e => e.Detalles)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.TipoProductoNavigation)
                    .WithMany(p => p.DetallePedido)
                    .HasForeignKey(d => d.TipoProducto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DetallePedido_DetallePedido");
            });

            modelBuilder.Entity<Factura>(entity =>
            {
                entity.HasKey(e => e.IdFactura);

                entity.Property(e => e.IdFactura).ValueGeneratedNever();

                entity.Property(e => e.Detalle)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.EstadodelPedido)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.FechaHoraEmision).HasColumnType("date");

                entity.Property(e => e.Nit)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Funcionario>(entity =>
            {
                entity.HasKey(e => e.IdFuncionario);

                entity.HasIndex(e => e.UserName, "IX_Funcionario")
                    .IsUnique();

                entity.HasIndex(e => e.Password, "IX_Funcionario_1")
                    .IsUnique();

                entity.Property(e => e.IdFuncionario).ValueGeneratedNever();

                entity.Property(e => e.Correo)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Rol)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Vehiculo).HasColumnName("vehiculo");

                entity.HasOne(d => d.VehiculoNavigation)
                    .WithMany(p => p.Funcionario)
                    .HasForeignKey(d => d.Vehiculo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Funcionario_Vehiculo");
            });

            modelBuilder.Entity<Localidad>(entity =>
            {
                entity.HasKey(e => e.IdLocalidad);

                entity.Property(e => e.IdLocalidad).ValueGeneratedNever();

                entity.Property(e => e.Barrio)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Calle)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Zona)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Pedido>(entity =>
            {
                entity.HasKey(e => e.IdPedido);

                entity.Property(e => e.IdPedido).ValueGeneratedNever();

                entity.Property(e => e.Calle)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.FechaHoraCreacion)
                    .HasColumnType("date")
                    .HasColumnName("fechaHoraCreacion");

                entity.Property(e => e.FechaHoraEntrega)
                    .HasColumnType("date")
                    .HasColumnName("fechaHoraEntrega");

                entity.Property(e => e.NombreCliente)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Numero)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.TelefonoCliente).HasColumnName("telefonoCliente");

                entity.HasOne(d => d.FacturaNavigation)
                    .WithMany(p => p.Pedido)
                    .HasForeignKey(d => d.Factura)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_factura_Pedido");

                entity.HasOne(d => d.IdPedidoNavigation)
                    .WithOne(p => p.Pedido)
                    .HasForeignKey<Pedido>(d => d.IdPedido)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pedido_DetallePedido");

                entity.HasOne(d => d.LocalidadNavigation)
                    .WithMany(p => p.Pedido)
                    .HasForeignKey(d => d.Localidad)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pedido_Localidad");

                entity.HasOne(d => d.PersonaNavigation)
                    .WithMany(p => p.Pedido)
                    .HasForeignKey(d => d.Persona)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Pedido_Persona");
            });

            modelBuilder.Entity<Persona>(entity =>
            {
                entity.HasKey(e => e.IdPersona);

                entity.Property(e => e.IdPersona).ValueGeneratedNever();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.NumeroIdentidad)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.IdPersonaNavigation)
                    .WithOne(p => p.Persona)
                    .HasForeignKey<Persona>(d => d.IdPersona)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Persona_Cliente");

                entity.HasOne(d => d.RolNavigation)
                    .WithMany(p => p.Persona)
                    .HasForeignKey(d => d.Rol)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Persona_Funcionario");
            });

            modelBuilder.Entity<Productos>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.PizzaFamiliar)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("pizzaFamiliar");

                entity.Property(e => e.PizzaMediana)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PizzaPequeña)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<TipoVehiculo>(entity =>
            {
                entity.HasKey(e => e.IdTipoVehi);

                entity.Property(e => e.IdTipoVehi).ValueGeneratedNever();

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Vehiculo>(entity =>
            {
                entity.HasKey(e => e.IdVehiculo);

                entity.Property(e => e.IdVehiculo).ValueGeneratedNever();

                entity.Property(e => e.Licencia)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Modelo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("modelo");

                entity.Property(e => e.Patente)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.TipoVehiculoNavigation)
                    .WithMany(p => p.Vehiculo)
                    .HasForeignKey(d => d.TipoVehiculo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Vehiculo_TipoVehiculo");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}