// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string Nit { get; set; }
        public string RazonSocial { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Localidad { get; set; }

        public virtual Localidad LocalidadNavigation { get; set; }
        public virtual Persona Persona { get; set; }
    }
}