// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class DetallePedido
    {
        public int IdDetallePedido { get; set; }
        public int Cantidad { get; set; }
        public int SubTotal { get; set; }
        public int TipoProducto { get; set; }
        public string Detalles { get; set; }

        public virtual Productos TipoProductoNavigation { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}