// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Factura
    {
        public Factura()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int IdFactura { get; set; }
        public DateTime FechaHoraEmision { get; set; }
        public string Detalle { get; set; }
        public string EstadodelPedido { get; set; }
        public string Nit { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}