// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Funcionario
    {
        public Funcionario()
        {
            Persona = new HashSet<Persona>();
        }

        public int IdFuncionario { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Correo { get; set; }
        public string Rol { get; set; }
        public int Vehiculo { get; set; }

        public virtual Vehiculo VehiculoNavigation { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
    }
}