// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Localidad
    {
        public Localidad()
        {
            Cliente = new HashSet<Cliente>();
            Pedido = new HashSet<Pedido>();
        }

        public int IdLocalidad { get; set; }
        public string Calle { get; set; }
        public string Barrio { get; set; }
        public string Zona { get; set; }

        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}