// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public string Numero { get; set; }
        public DateTime FechaHoraCreacion { get; set; }
        public DateTime FechaHoraEntrega { get; set; }
        public string Calle { get; set; }
        public int Persona { get; set; }
        public int Factura { get; set; }
        public int Localidad { get; set; }
        public string NombreCliente { get; set; }
        public int TelefonoCliente { get; set; }
        public int Detalle { get; set; }

        public virtual Factura FacturaNavigation { get; set; }
        public virtual DetallePedido IdPedidoNavigation { get; set; }
        public virtual Localidad LocalidadNavigation { get; set; }
        public virtual Persona PersonaNavigation { get; set; }
    }
}