// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Productos
    {
        public Productos()
        {
            DetallePedido = new HashSet<DetallePedido>();
        }

        public int Id { get; set; }
        public string PizzaFamiliar { get; set; }
        public string PizzaMediana { get; set; }
        public string PizzaPequeña { get; set; }

        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
    }
}