// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Delivery.Models
{
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            Funcionario = new HashSet<Funcionario>();
        }

        public int IdVehiculo { get; set; }
        public string Patente { get; set; }
        public string Modelo { get; set; }
        public int TipoVehiculo { get; set; }
        public string Licencia { get; set; }

        public virtual TipoVehiculo TipoVehiculoNavigation { get; set; }
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}